repos:
  # Format C++ code with Clang-Format - automatically applying the changes
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        args:
        - --style=Mozilla
        exclude: ^ext/

  # Add some general purpose useful hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # Make sure that contained YAML files are well-formed
      - id: check-yaml
      # Trim trailing whitespace of all sorts
      - id: trailing-whitespace
      # Apply a file size limit of 500kB
      - id: check-added-large-files
      # Simple parser validation of e.g. pyproject.toml
      - id: check-toml
      # Unify file endings
      - id: end-of-file-fixer
